# Generated by Django 5.2.1 on 2025-06-08 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_alter_customer_options_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
