# Generated by Django 5.2.2 on 2025-06-14 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__last_name", "user__first_name"],
                "permissions": [("view_history", "Can view history")],
            },
        ),
    ]
